# Support Vector Regression (SVR)

## Importing the libraries

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [13]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [14]:
dataset.head(5), dataset.describe()


(      AT      V       AP     RH      PE
 0  14.96  41.76  1024.07  73.17  463.26
 1  25.18  62.96  1020.04  59.08  444.37
 2   5.11  39.40  1012.16  92.14  488.56
 3  20.86  57.32  1010.24  76.64  446.48
 4  10.82  37.50  1009.23  96.62  473.90,
                 AT            V           AP           RH           PE
 count  9568.000000  9568.000000  9568.000000  9568.000000  9568.000000
 mean     19.651231    54.305804  1013.259078    73.308978   454.365009
 std       7.452473    12.707893     5.938784    14.600269    17.066995
 min       1.810000    25.360000   992.890000    25.560000   420.260000
 25%      13.510000    41.740000  1009.100000    63.327500   439.750000
 50%      20.345000    52.080000  1012.940000    74.975000   451.550000
 75%      25.720000    66.540000  1017.260000    84.830000   468.430000
 max      37.110000    81.560000  1033.300000   100.160000   495.760000)

In [15]:
y = y.reshape(len(y),1)

## Splitting the dataset into the Training set and Test set

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [17]:
X_train, X_test

(array([[  21.92,   49.02, 1009.29,   88.56],
        [  11.09,   40.43, 1025.47,   74.97],
        [   8.49,   39.61, 1021.05,   87.74],
        ...,
        [  27.79,   69.23, 1012.86,   45.71],
        [  12.26,   41.5 , 1014.87,   89.41],
        [  11.75,   40.55, 1018.09,   97.7 ]]),
 array([[  19.64,   48.06, 1014.81,   74.96],
        [  28.26,   69.23, 1013.01,   42.1 ],
        [  27.98,   67.17, 1007.32,   75.29],
        ...,
        [   8.02,   39.04, 1018.49,   68.07],
        [  26.48,   69.14, 1009.31,   84.11],
        [  15.34,   71.14, 1019.79,   77.56]]))

In [18]:
y_train, y_test

(array([[443.31],
        [490.96],
        [483.94],
        ...,
        [435.06],
        [471.13],
        [472.43]]),
 array([[455.27],
        [436.31],
        [440.68],
        ...,
        [479.53],
        [435.76],
        [457.1 ]]))

## Feature Scaling

In [19]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

## Training the SVR model on the Training set

In [20]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

## Predicting the Test set results

In [21]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[456.77 455.27]
 [437.11 436.31]
 [434.62 440.68]
 ...
 [483.16 479.53]
 [435.35 435.76]
 [458.55 457.1 ]]


## Evaluating the Model Performance

In [22]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9468461924240114